In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [1]:
from cvxopt import matrix, solvers

Solving problem:

![](https://cvxopt.org/userguide/_images/math/e7b0acebcd74fc3b4ec4b01f916c596976722c78.png)

Reference: https://cvxopt.org/userguide/coneprog.html#semidefinite-programming

In [2]:
c = matrix([1.,-1.,1.])

G = [ matrix([[-7., -11., -11., 3.],
              [ 7., -18., -18., 8.],
              [-2.,  -8.,  -8., 1.]]) ]

G += [ matrix([[-21., -11.,   0., -11.,  10.,   8.,   0.,   8., 5.],
               [  0.,  10.,  16.,  10., -10., -10.,  16., -10., 3.],
               [ -5.,   2., -17.,   2.,  -6.,   8., -17.,  8., 6.]]) ]

h = [ matrix([[33., -9.], [-9., 26.]]) ]
h += [ matrix([[14., 9., 40.], [9., 91., 10.], [40., 10., 15.]]) ]

sol = solvers.sdp(c, Gs=G, hs=h)

print(sol['x'])
print(sol['zs'][0])
print(sol['zs'][1])

     pcost       dcost       gap    pres   dres   k/t
 0: -1.2037e+00 -1.8539e+02  2e+02  2e-16  8e+00  1e+00
 1: -1.2937e+00 -6.8551e+00  5e+00  5e-16  3e-01  3e-02
 2: -2.8964e+00 -3.7331e+00  7e-01  9e-16  4e-02  5e-02
 3: -3.0150e+00 -3.2556e+00  2e-01  7e-16  1e-02  2e-02
 4: -3.1389e+00 -3.1932e+00  5e-02  4e-16  3e-03  5e-03
 5: -3.1533e+00 -3.1547e+00  1e-03  2e-15  7e-05  1e-04
 6: -3.1535e+00 -3.1536e+00  5e-05  8e-16  3e-06  6e-06
 7: -3.1535e+00 -3.1535e+00  1e-06  6e-16  7e-08  2e-07
Optimal solution found.
[-3.68e-01]
[ 1.90e+00]
[-8.88e-01]

[ 3.96e-03 -4.34e-03]
[-4.34e-03  4.75e-03]

[ 5.58e-02 -2.41e-03  2.42e-02]
[-2.41e-03  1.04e-04 -1.05e-03]
[ 2.42e-02 -1.05e-03  1.05e-02]



Now, nuclear norm $||A||_*$ can be computed from the following semidefinite program:

$$
\begin{equation*}
\begin{aligned}
& \underset{Y}{\text{maximize}}
& & TrA^TY \\
& \text{subject to}
& &  \begin{bmatrix}I_{n1} & Y \\Y^T & I_{n2} \end{bmatrix}  \succcurlyeq 0
\end{aligned}
\end{equation*}
$$

or its dual:

$$
\begin{equation*}
\begin{aligned}
& \underset{W_1, W_1}{\text{minimize}}
& & \frac{1}{2}(TrW_1 + TrW_2) \\
& \text{subject to}
& &  \begin{bmatrix}W_1 & A \\A^T & W_2 \end{bmatrix}  \succcurlyeq 0
\end{aligned}
\end{equation*}
$$

Letting $A = \begin{bmatrix}1 & 0 \\0 & 0 \end{bmatrix}$:

$$
\begin{equation*}
\begin{aligned}
& \underset{}{\text{minimize}}
& & \frac{1}{2}(w_{11}^1 + w_{22}^1 + w_{11}^2 + w_{22}^2) \\
& \text{subject to}
& &  \begin{bmatrix}
    w_{11}^1 & w_{12}^1 & 1 & 0 \\
    w_{21}^1 & w_{22}^1 & 0 & 0 \\
    1 & 0 & w_{11}^2 & w_{12}^2 \\
    0 & 0 & w_{21}^2 & w_{22}^2
\end{bmatrix}  \succcurlyeq 0
\end{aligned}
\end{equation*}
$$

It is evident that $w_{21}^1 = w_{12}^1$ and $w_{21}^2 = w_{12}^2$ for constraint matrix to be symmetric.